# it is for the WSL and powershell
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
# A minimal left prompt
#format = '\[$username$hostname$directory$git_branch$git_status\]$character'
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
#right_format = """$all"""

format = '\[$username$hostname$directory$git_branch$git_status$cmd_duration$jobs\]$character' 

[directory]
style = 'white bold'
truncation_length = 1
read_only =' '

[character]
#format = '\$ '
success_symbol = '[\$](white bold)'
error_symbol = '[\$](#eba0ac bold)'

[git_branch]
style = 'fg:#b4befe'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:#b4befe'
format = '([$all_status$ahead_behind]($style) )'

[username]
style_user = 'white bold'
style_root = 'white bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](white bold) '

[cmd_duration]
style = 'fg:#f5e0dc' 
format = ' [$duration]($style) '

[jobs]
symbol = '  '
style = 'fg:#eba0ac'
number_threshold = 1
format = ' [$symbol]($style) '


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


#export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
#eval "$(starship init zsh)"


